version: 2.0

# jobs refer to a single execution of the build

jobs:
  # build is the name of the job....they can be multiple and unique
  build:
    # builds occur in a docker container
    docker:
      - image: circleci/python:3.7

    working_directory: ~/mypersonalapp-django


    # series/ list of steps done for the build
    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv mypersonalapp
            . mypersonalapp/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
    
      - run:
          name: Install awscli
          command: sudo pip3 install awscli
      
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            . mypersonalapp/bin/activate
            cd mypersonalapp
            python3 manage.py test
            coverage report
          
      - run:
          name: tests-results
          command: |
            store_test_results:
              path: test-results
            store_artifacts:
              path: test-results
              destination: tr1
 